routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['middleware' => 'admin'], function () {
        //Users
        Route::get('users', 'UserController@index')->name('users');
        Route::get('users/create', 'UserController@create')->name('users.create');
        Route::post('users', 'UserController@store')->name('users.store');
        Route::get('users/{user}', 'UserController@show')->name('users.show');
        Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
        Route::put('users/{user}', 'UserController@update')->name('users.update');
        Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

        Route::get('permissions', 'PermissionController@index')->name('permissions');
        Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');

        Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
        Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');

        Route::get('deliveryProfiles', 'DeliveryProfileController@index')->name('delivery_profiles');
        Route::get('deliveryProfiles/{deliveryProfile}', 'DeliveryProfileController@show')->name('delivery_profiles.show');
        Route::get('deliveryProfiles/{deliveryProfile}/edit', 'DeliveryProfileController@edit')->name('delivery_profiles.edit');
        Route::put('deliveryProfiles/{deliveryProfile}', 'DeliveryProfileController@update')->name('delivery_profiles.update');

        Route::get('supports', 'SupportController@index')->name('supports');
        Route::get('supports/{support}', 'SupportController@show')->name('supports.show');

        Route::get('categories', 'CategoryController@index')->name('categories');
        Route::get('categories/create', 'CategoryController@create')->name('categories.create');
        Route::post('categories', 'CategoryController@store')->name('categories.store');
        Route::get('categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
        Route::put('categories/{category}', 'CategoryController@update')->name('categories.update');

        Route::get('coupons', 'CouponController@index')->name('coupons');
        Route::get('coupons/create', 'CouponController@create')->name('coupons.create');
        Route::post('coupons', 'CouponController@store')->name('coupons.store');
        Route::get('coupons/{coupon}/edit', 'CouponController@edit')->name('coupons.edit');
        Route::put('coupons/{coupon}', 'CouponController@update')->name('coupons.update');
        Route::delete('coupons/{coupon}', 'CouponController@destroy')->name('coupons.destroy');

        Route::get('menuitems', 'MenuItemController@index')->name('menuitems');
        Route::get('menuitems/create', 'MenuItemController@create')->name('menuitems.create');
        Route::post('menuitems', 'MenuItemController@store')->name('menuitems.store');
        Route::get('menuitems/{menuitem}', 'MenuItemController@show')->name('menuitems.show');
        Route::get('menuitems/{menuitem}/edit', 'MenuItemController@edit')->name('menuitems.edit');
        Route::put('menuitems/{menuitem}', 'MenuItemController@update')->name('menuitems.update');
        Route::put('menuitems/{menuitem}/quick-approve', 'MenuItemController@quickApprove')->name('menuitems.quickApprove');

        #Route::get('settings', 'SettingController@index')->name('settings');
        Route::get('settings/{setting}/edit', 'SettingController@edit')->name('settings.edit');
        Route::get('settings', 'SettingController@settings')->name('settings');
        Route::put('settings/update-env', 'SettingController@updateEnv')->name('settings.updateEnv');
        Route::put('settings/update-setting', 'SettingController@updateSetting')->name('settings.updateSetting');

        Route::post('json/notifications/read', 'Json\NotificationController@readNotifications')->name('json.notifications.read');
        Route::post('json/notifications/delete', 'Json\NotificationController@deleteNotifications')->name('json.notifications.delete');
        Route::post('json/dashboard/orders-chart-data', 'Json\DashboardController@ordersChartData')->name('json.dashboard.ordersChartData');
        Route::post('json/dashboard/users-chart-data', 'Json\DashboardController@usersChartData')->name('json.dashboard.usersChartData');
        Route::put('json/orders/{order}', 'Json\OrderController@update')->name('json.orders.update');
    });

    Route::group(['middleware' => 'store'], function () {
        Route::get('stores', 'StoreController@index')->name('stores');
        Route::get('stores/{store}', 'StoreController@show')->name('stores.show');
        Route::get('stores/{store}/edit', 'StoreController@edit')->name('stores.edit');
        Route::put('stores/{store}', 'StoreController@update')->name('stores.update');

        Route::get('menuitems', 'MenuItemController@index')->name('menuitems');
        Route::get('menuitems/{menuitem}', 'MenuItemController@show')->name('menuitems.show');
        Route::get('menuitems/{menuitem}/edit', 'MenuItemController@edit')->name('menuitems.edit');
        Route::put('menuitems/{menuitem}', 'MenuItemController@update')->name('menuitems.update');

        Route::get('ratings', 'RatingController@index')->name('ratings');
        Route::get('ratings/{id}', 'RatingController@destroy')->name('ratings.destroy');

        Route::get('orders', 'OrderController@index')->name('orders');
        Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
        Route::get('orders/{order}/edit', 'OrderController@edit')->name('orders.edit');
        Route::put('orders/{order}', 'OrderController@update')->name('orders.update');

        Route::get('earnings', 'EarningController@index')->name('earnings');
        Route::get('earnings/{earning}', 'EarningController@show')->name('earnings.show');

        Route::get('ratings', 'RatingController@index')->name('ratings');
        Route::get('ratings/{id}', 'RatingController@destroy')->name('ratings.destroy');

        Route::get('bankdetails', 'BankDetailController@index')->name('bankdetails');
        Route::get('bankdetails/{bankdetail}', 'BankDetailController@show')->name('bankdetails.show');
        Route::get('bankdetails/{bankdetail}/edit', 'BankDetailController@edit')->name('bankdetails.edit');
        Route::put('bankdetails/{bankdetail}', 'BankDetailController@update')->name('bankdetails.update');
    });
});


Route::get('/', 'HomeController@index');

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.admin')

@section('content')
    <!-- page content -->
    <!-- top tiles -->
    <div class="row tile_count">
        <div class="col-md-4 col-sm-4 col-xs-4 tile_stats_count">
            <a href="{{ route('admin.users') }}">
                <span class="count_top"><i class="fa fa-users"></i> Total Users</span>
                <div class="count green">{{ $counts['customers'] }}</div>
            </a>
        </div>

        <div class="col-md-4 col-sm-4 col-xs-4 tile_stats_count">
            <a href="{{ route('admin.stores') }}">
                <span class="count_top"><i class="fa fa-users"></i> Total Stores</span>
                <div class="count green">{{ $counts['stores'] }}</div>
            </a>
        </div>

        <div class="col-md-4 col-sm-4 col-xs-4 tile_stats_count">
            <a href="{{ route('admin.delivery_profiles') }}">
                <span class="count_top"><i class="fa fa-users"></i> Total Delivery Profiles</span>
                <div class="count green">{{ $counts['deliveryProfiles'] }}</div>
            </a>
        </div>

    </div>


    <div class="row tile_count">
        <div class="col-md-4 col-sm-4 col-xs-4 tile_stats_count">
            <a href="{{ route('admin.orders') }}">
                <span class="count_top"><i class="fa fa-users"></i> Total Orders</span>
                <div class="count green">{{ $orderCounts['total'] }}</div>
            </a>
        </div>

        <div class="col-md-4 col-sm-4 col-xs-4 tile_stats_count">
            <a href="{{ route('admin.orders') }}">
                <span class="count_top"><i class="fa fa-users"></i> Total Orders Cancelled</span>
                <div class="count green">{{ $orderCounts['cancelled'] }}</div>
            </a>
        </div>

        <div class="col-md-4 col-sm-4 col-xs-4 tile_stats_count">
            <a href="{{ route('admin.orders') }}">
                <span class="count_top"><i class="fa fa-users"></i> Total Orders Pending</span>
                <div class="count green">{{ $orderCounts['pending'] }}</div>
            </a>
        </div>

    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph x_panel">
                <div class="row x_title">
                    <div class="col-md-3">
                        <h3>Active Orders</h3>
                    </div>
                </div>
                <div class="x_content">
                    <div class="demo-container">
                        <div id="map" class="demo-placeholder" style="height:800px"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Orders placed</h2>
                    <div class="filter">
                        <div id="orders-chart-range" class="pull-right"
                             style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                            <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                            <span>December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-md-9 col-sm-12 col-xs-12">
                        <div class="demo-container" style="height:280px">
                            <div id="orders_chart" class="demo-placeholder"></div>
                        </div>
                        <div class="tiles">

                            <div class="col-md-4 tile">
                                <span>Total Orders</span>
                                <h2>{{ $orderCounts['total'] }}</h2>
                                <span class="orders_sparkline graph" style="height: 160px;">
                                    <canvas width="200" height="60"
                                            style="display: inline-block; vertical-align: top; width: 94px; height: 30px;"></canvas>
                                </span>
                            </div>

                            <div class="col-md-4 tile">
                                <span>Total Earnings</span>
                                <h2>{{ $earningsCount['total'] }}</h2>
                                <span class="revenue_sparkline graph" style="height: 160px;">
                                    <canvas width="200" height="60"
                                            style="display: inline-block; vertical-align: top; width: 94px; height: 30px;"></canvas>
                                </span>
                            </div>

                            <div class="col-md-4 tile">
                                <span>Total Stores</span>
                                <h2>{{$counts['stores']}}</h2>
                                <span class="earnings_sparkline graph" style="height: 160px;">
                                    <canvas width="200" height="60"
                                            style="display: inline-block; vertical-align: top; width: 94px; height: 30px;"></canvas>
                                </span>
                            </div>
                        </div>

                    </div>

                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <div>
                            <div class="x_title">
                                <h2>Trending Stores</h2>
                                <div class="clearfix"></div>
                            </div>
                            <ul class="list-unstyled top_profiles scroll-view">
                                @foreach($trendingStores as $trendingStore)
                                    <li class="media event">
                                        <a class="pull-left border-aero profile_thumb">
                                            <i class="fa fa-cutlery aero"></i>
                                        </a>
                                        <div class="media-body" style="text-transform:capitalize">
                                            <a class="title"
                                               href="{{ route('admin.stores.show', ['store' => $trendingStore->store->id]) }}">{{ $trendingStore->store->name }}</a>
                                            <p>
                                                <small>{{ $trendingStore->total }} sales</small>
                                            </p>
                                        </div>
                                    </li>
                                @endforeach
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="dashboard_graph x_panel">
                <div class="row x_title">
                    <div class="col-md-6">
                        <h3>User Registrations</h3>
                    </div>
                    <div class="col-md-6">
                        <div id="users-chart-range" class="pull-right"
                             style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                            <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                            <span>December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
                        </div>
                    </div>
                </div>
                <div class="x_content">
                    <div class="demo-container" style="height:250px">
                        <div id="users_chart" class="demo-placeholder"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    @parent

    <script type="text/javascript">
        var ORDERS_DATA = [];
        @foreach($ordersChartData as $orderChartData)
        ORDERS_DATA.push([new Date("{{ $orderChartData->created_at }}").getTime(), {{ $orderChartData->total }}]);
                @endforeach

        var USERS_DATA = [];
        @foreach($usersChartData as $userChartData)
        USERS_DATA.push([new Date("{{ $userChartData->created_at }}").getTime(), {{ $userChartData->total }}]);
                @endforeach

        var URL_FETCH_ORDERS_CHART_DATA = "{{ route('admin.json.dashboard.ordersChartData') }}";
        var URL_FETCH_USERS_CHART_DATA = "{{ route('admin.json.dashboard.usersChartData') }}";
    </script>

    {{ Html::script(mix('assets/admin/js/dashboard.js')) }}

    <script>
        // map
        var map;
        var markers = [];
        var infoWindow, marker;

        function initMap() {
            var myLatLng = {
                lat: 28.66,
                lng: 70.60
            };

            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: myLatLng
            });

            @foreach($activeOrders as $order)
                marker = new google.maps.Marker({
                map: map,
                position: {
                    lat: parseFloat('{{ $order->address->latitude }}'),
                    lng: parseFloat('{{ $order->address->longitude }}')
                }
            });

            marker.addListener('click', function () {
                new google.maps.InfoWindow({
                    content: '<div class="container col-xs-10">' +
                    '<div class="row"><div class="col-xs-12"><div class="page-header"><h3><a href="{{ route('admin.orders.show', ['id' => $order->id]) }}">Order#{{ $order->id }}</h3></div></div></div>' +
                    '<div class="row form-group"><div class="col-xs-1 pull-left"><i class="fa fa-cutlery"></i></div><div class="col-xs-9 pull-left"><a href="{{ route('admin.stores.show', ['id' => $order->store->id]) }}">{{ $order->store->name }}</a></div></div>' +
                    '<div class="row form-group"><div class="col-xs-1 pull-left"><i class="fa fa-user-o"></i></div><div class="col-xs-9 pull-left"><a href="{{ route('admin.users.show', ['id' => $order->user->id]) }}">{{ $order->user->name }}</a></div></div>' +
                    '<div class="row form-group"><div class="col-xs-1 pull-left"><i class="fa fa-info-circle"></i></div><div class="col-xs-9 pull-left" style="text-transform:capitalize">{{ $order->status }}</div></div>' +
                    '</div></div>'
                }).open(map, this);
            })
            markers.push(marker);
                    @endforeach

            var bounds = new google.maps.LatLngBounds();
            for (var i = 0; i < markers.length; i++) {
                bounds.extend(markers[i].getPosition());
            }

            //center the map to the geometric center of all markers
            map.setCenter(bounds.getCenter());
            // adjust zoom levels
            google.maps.event.addListenerOnce(map, 'bounds_changed', function (event) {
                this.setZoom(map.getZoom() - 1);

                if (this.getZoom() > 12) {
                    this.setZoom(12);
                }
            });
            map.fitBounds(bounds);
        }
    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBQgDBgxgMLaf2Xp173VIhuKVzAw_vPCyY&callback=initMap"
            type="text/javascript"></script>
@endsection

@section('styles')
    @parent
    {{ Html::style(mix('assets/admin/css/dashboard.css')) }}
@endsection

resources/views/admin/permissions.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.membership.title'))

@section('content')
    <div class="row">
        <table class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>ID</th>
                <th>@sortablelink('email', __('views.membership.table_header_0'),['page' => $users->currentPage()])</th>
                <th>@sortablelink('name',  __('views.membership.table_header_1'),['page' => $users->currentPage()])</th>
                <th>{{ __('views.membership.table_header_2') }}</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->name }}</td>
                    <td>
                        @if($user->hasRoles(config('protection.except_roles')))
                            <div class="line_30 h5">
                                &nbsp;
                            </div>
                        @else
                            <a title="Repeat validation" class="btn btn-default pull-right" href="{{ route('admin.permissions.repeat',$user) }}">
                                <i class="fa fa-refresh" aria-hidden="true"></i>
                            </a>
                            @if($user->protectionValidation)
                                <table class="table table-striped table-bordered dt-responsive nowrap">
                                    <thead>
                                    <tr>
                                        <th>{{ __('views.membership.table_header_3') }}</th>
                                        <th>{{ __('views.membership.table_header_4') }}</th>
                                        <th>{{ __('views.membership.table_header_5') }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    @foreach($user->protectionValidation->validation_result as $result)
                                        <tr>
                                            <td style="width: 30%">{{ $result['productModuleNumber'] }}</td>
                                            <td style="width: 10%">
                                                @if($result['valid'])
                                                    <span class="label label-primary">{{ __('views.membership.valid') }}</span>
                                                @else
                                                    <span class="label label-danger">{{ __('views.membership.not_valid') }}</span>
                                                @endif
                                            </td>
                                            <td>
                                                {{ isset($result['expires'])?$result['expires']:''  }}
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            @else
                                <div class="line_30 h4">
                                    Not validated
                                </div>
                            @endif
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            Powered by <a href="http://netlicensing.io/?utm_source=Laravel_Boilerplate&utm_medium=github&utm_campaign=laravel_boilerplate&utm_content=poweredby" target="_blank"/>Labs64 NetLicensing</a>
        </div>
        <div class="pull-right">
            {{ $users->links() }}
        </div>
        <div>
            <h4>How To</h4>
            <ul>
              <li>Manage available membership plans - <a href="https://go.netlicensing.io/console/v2/content/vendor/licensetemplate.xhtml?filterkey=productModuleNumber&filtervalue={{ config('protection.membership.product_module_number') }}" target="_blank"/>NetLicensing Management Console » License Templates</a></li>
              <li>View and manage registered users - <a href="https://go.netlicensing.io/console/v2/content/vendor/licensee.xhtml?filterkey=productNumber&filtervalue={{ config('protection.product_number') }}" target="_blank"/>NetLicensing Management Console » Licensees</a></li>
            </ul>
        </div>
    </div>
@endsection

resources/views/admin/unauthorized.blade.php
@extends('admin.layouts.admin')

@section('content')
    <h2>You are unauthorized to perform this action. </h2>
    <h3>This feature is working perfectly but disabled right now to prevent spam.</h3>
    <a class="btn btn-primary" href="{{ URL::previous() }}"> Go Back</a>
@endsection