routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['middleware' => 'admin'], function () {
        //Users
        Route::get('users', 'UserController@index')->name('users');
        Route::get('users/create', 'UserController@create')->name('users.create');
        Route::post('users', 'UserController@store')->name('users.store');
        Route::get('users/{user}', 'UserController@show')->name('users.show');
        Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
        Route::put('users/{user}', 'UserController@update')->name('users.update');
        Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

        Route::get('permissions', 'PermissionController@index')->name('permissions');
        Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');

        Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
        Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');

        Route::get('deliveryProfiles', 'DeliveryProfileController@index')->name('delivery_profiles');
        Route::get('deliveryProfiles/{deliveryProfile}', 'DeliveryProfileController@show')->name('delivery_profiles.show');
        Route::get('deliveryProfiles/{deliveryProfile}/edit', 'DeliveryProfileController@edit')->name('delivery_profiles.edit');
        Route::put('deliveryProfiles/{deliveryProfile}', 'DeliveryProfileController@update')->name('delivery_profiles.update');

        Route::get('supports', 'SupportController@index')->name('supports');
        Route::get('supports/{support}', 'SupportController@show')->name('supports.show');

        Route::get('categories', 'CategoryController@index')->name('categories');
        Route::get('categories/create', 'CategoryController@create')->name('categories.create');
        Route::post('categories', 'CategoryController@store')->name('categories.store');
        Route::get('categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
        Route::put('categories/{category}', 'CategoryController@update')->name('categories.update');

        Route::get('coupons', 'CouponController@index')->name('coupons');
        Route::get('coupons/create', 'CouponController@create')->name('coupons.create');
        Route::post('coupons', 'CouponController@store')->name('coupons.store');
        Route::get('coupons/{coupon}/edit', 'CouponController@edit')->name('coupons.edit');
        Route::put('coupons/{coupon}', 'CouponController@update')->name('coupons.update');
        Route::delete('coupons/{coupon}', 'CouponController@destroy')->name('coupons.destroy');

        Route::get('menuitems', 'MenuItemController@index')->name('menuitems');
        Route::get('menuitems/create', 'MenuItemController@create')->name('menuitems.create');
        Route::post('menuitems', 'MenuItemController@store')->name('menuitems.store');
        Route::get('menuitems/{menuitem}', 'MenuItemController@show')->name('menuitems.show');
        Route::get('menuitems/{menuitem}/edit', 'MenuItemController@edit')->name('menuitems.edit');
        Route::put('menuitems/{menuitem}', 'MenuItemController@update')->name('menuitems.update');
        Route::put('menuitems/{menuitem}/quick-approve', 'MenuItemController@quickApprove')->name('menuitems.quickApprove');

        #Route::get('settings', 'SettingController@index')->name('settings');
        Route::get('settings/{setting}/edit', 'SettingController@edit')->name('settings.edit');
        Route::get('settings', 'SettingController@settings')->name('settings');
        Route::put('settings/update-env', 'SettingController@updateEnv')->name('settings.updateEnv');
        Route::put('settings/update-setting', 'SettingController@updateSetting')->name('settings.updateSetting');

        Route::post('json/notifications/read', 'Json\NotificationController@readNotifications')->name('json.notifications.read');
        Route::post('json/notifications/delete', 'Json\NotificationController@deleteNotifications')->name('json.notifications.delete');
        Route::post('json/dashboard/orders-chart-data', 'Json\DashboardController@ordersChartData')->name('json.dashboard.ordersChartData');
        Route::post('json/dashboard/users-chart-data', 'Json\DashboardController@usersChartData')->name('json.dashboard.usersChartData');
        Route::put('json/orders/{order}', 'Json\OrderController@update')->name('json.orders.update');
    });

    Route::group(['middleware' => 'store'], function () {
        Route::get('stores', 'StoreController@index')->name('stores');
        Route::get('stores/{store}', 'StoreController@show')->name('stores.show');
        Route::get('stores/{store}/edit', 'StoreController@edit')->name('stores.edit');
        Route::put('stores/{store}', 'StoreController@update')->name('stores.update');

        Route::get('menuitems', 'MenuItemController@index')->name('menuitems');
        Route::get('menuitems/{menuitem}', 'MenuItemController@show')->name('menuitems.show');
        Route::get('menuitems/{menuitem}/edit', 'MenuItemController@edit')->name('menuitems.edit');
        Route::put('menuitems/{menuitem}', 'MenuItemController@update')->name('menuitems.update');

        Route::get('ratings', 'RatingController@index')->name('ratings');
        Route::get('ratings/{id}', 'RatingController@destroy')->name('ratings.destroy');

        Route::get('orders', 'OrderController@index')->name('orders');
        Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
        Route::get('orders/{order}/edit', 'OrderController@edit')->name('orders.edit');
        Route::put('orders/{order}', 'OrderController@update')->name('orders.update');

        Route::get('earnings', 'EarningController@index')->name('earnings');
        Route::get('earnings/{earning}', 'EarningController@show')->name('earnings.show');

        Route::get('ratings', 'RatingController@index')->name('ratings');
        Route::get('ratings/{id}', 'RatingController@destroy')->name('ratings.destroy');

        Route::get('bankdetails', 'BankDetailController@index')->name('bankdetails');
        Route::get('bankdetails/{bankdetail}', 'BankDetailController@show')->name('bankdetails.show');
        Route::get('bankdetails/{bankdetail}/edit', 'BankDetailController@edit')->name('bankdetails.edit');
        Route::put('bankdetails/{bankdetail}', 'BankDetailController@update')->name('bankdetails.update');
    });
});


Route::get('/', 'HomeController@index');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\Auth\Registered;
use App\Http\Requests\Admin\UserRequest;
use App\Models\Auth\Role\Role;
use App\Models\Auth\User\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\UnauthorizedException;
use Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::whereRaw('1=1');

        if($request->search) {
            $users = $users->where('name', 'like', '%'. $request->search . '%')
                ->orWhere('mobile_number', 'like', '%'. $request->search . '%')
                ->orWhere('email', 'like', '%'. $request->search . '%');
        }

        if($request->role) {
            $role = $request->role;
            $users = $users->whereHas('roles', function ($query) use ($role){
                $query->where('name', $role);
            });
        }

        return view('admin.users.index', ['users' => $users->with('roles')->sortable(['created_at' => 'desc'])->paginate()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create', ['roles' => Role::get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserRequest $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function store(UserRequest $request)
    {
        $user = new User();
        $user->name = $request->get('name');
        $user->mobile_number = $request->get('mobile_number');
        $user->email = $request->get('email');

        if ($request->has('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        $user->mobile_verified = $request->get('mobile_verified', 0);

        $user->save();

        $user->roles()->attach($request->get('role'));

        event(new Registered($user, Role::find($request->get('role'))->name));

        return redirect()->intended(route('admin.users'));
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(User $user)
    {
        return view('admin.users.show', ['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', ['user' => $user, 'roles' => Role::get()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param User $user
     * @return mixed
     */
    public function update(Request $request, User $user)
    {
        if(env('ADMIN_USER_EDIT_DISABLED', true)) {
            return view('admin.unauthorized');
        }

        $validator = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255',
            'mobile_number' => 'required|max:255',
            'mobile_verified' => 'sometimes|boolean',
            'active' => 'sometimes|boolean',
            'confirmed' => 'sometimes|boolean',
        ]);

        $validator->sometimes('email', 'unique:users', function ($input) use ($user) {
            return strtolower($input->email) != strtolower($user->email);
        });

        $validator->sometimes('mobile_number', 'unique:users', function ($input) use ($user) {
            return strtolower($input->mobile_number) != strtolower($user->mobile_number);
        });

        $validator->sometimes('password', 'min:6|confirmed', function ($input) {
            return $input->password;
        });

        if ($validator->fails()) return redirect()->back()->withErrors($validator->errors());

        $user->name = $request->get('name');
        $user->email = $request->get('email');
        $user->mobile_number = $request->get('mobile_number');

        if ($request->has('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        $user->mobile_verified = $request->get('mobile_verified', 0);
        $user->active = $request->get('active', 0);
        $user->confirmed = $request->get('confirmed', 0);

        $user->save();

        //roles
        if ($request->has('roles')) {
            $user->roles()->detach();

            if ($request->get('roles')) {
                $user->roles()->attach($request->get('roles'));
            }
        }

        return redirect()->intended(route('admin.users'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return void
     */
    public function destroy(User $user)
    {
        if(Auth::user()->hasRole('administrator') && !$user->hasRole('administrator')) {
            $user->forceDelete();
        }
        return redirect()->intended(route('admin.users'));
    }

    /**
     * Delete notifications
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function clearNotification(Request $request)
    {
        Auth::user()->unreadNotifications->where('type', $request->type)->markAsRead();
        return response()->json(["success" => 1]);
    }
}

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\ApiStoreUpdateRequest;
use App\Models\Store;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display the store of current logged in user
     *
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        return response()->json(Auth::user());
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $user = Auth::user();
        $user->fill($request->only(['fcm_registration_id']));
        $user->save();

        return response()->json($user);
    }
}

resources/views/admin/users/index.blade.php
@extends('admin.layouts.admin')

@section('title')
    Users &nbsp; <a class="btn btn-primary" href="{{ route('admin.users.create') }}"><i class="fa fa-plus-circle"></i>
        Add</a>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 20px">
            {{ Form::open(['route'=>['admin.users'],'method' => 'get','class'=>'form-horizontal form-label-left']) }}
            <div class="form-group">
                <label class="control-label col-sm-3 col-xs-12" for="search">
                    Search
                </label>
                <div class="col-sm-4 col-xs-12">
                    <input id="search" type="text" class="form-control col-md-7 col-xs-12"
                           placeholder="Search for name, mobile, email"
                           name="search" required value="{{ app('request')->input('search')  }}">
                </div>
                <div class="col-sm-5 col-xs-12">
                    <button type="submit" class="btn btn-success"><i class="fa fa-search"></i> Filter</button>
                    <a title="Clear" class="btn btn-default" href="{{ url_without_query_param('search')  }}"><i
                                class="fa fa-remove"></i></a>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3 col-xs-12">
                    Role
                </label>
                <div class="col-sm-9 col-xs-12">
                    <a class="btn btn-primary @if(request('role') == 'owner') active @endif"
                       href="{{ app('request')->fullUrlWithQuery(['role' => 'owner'])  }}"><i class="fa fa-cutlery"></i>
                        Store</a>
                    <a class="btn btn-info @if(request('role') == 'delivery') active @endif"
                       href="{{ app('request')->fullUrlWithQuery(['role' => 'delivery'])  }}"><i
                                class="fa fa-motorcycle"></i> Delivery</a>
                    <a class="btn btn-success @if(request('role') == 'customer') active @endif"
                       href="{{ app('request')->fullUrlWithQuery(['role' => 'customer'])  }}"><i class="fa fa-user-o"></i>
                        User</a>
                    <a title="Clear" class="btn btn-default" href="{{ url_without_query_param('role')  }}"><i
                                class="fa fa-remove"></i></a>
                </div>
            </div>
            {{ Form::close() }}
        </div>

        <table class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0"
               width="100%" style="text-align: center">
            <thead>
            <tr>
                <th>@sortablelink('email', __('views.admin.users.index.table_header_0'),['page' =>
                    $users->currentPage()])
                </th>
                <th>Mobile</th>
                <th>@sortablelink('name', 'Name',['page' => $users->currentPage()])</th>
                <th>{{ __('views.admin.users.index.table_header_2') }}</th>
                <th>Mobile Verified</th>
                <th>Quick Links</th>
                {{--<th>@sortablelink('active', __('views.admin.users.index.table_header_3'),['page' => $users->currentPage()])</th>--}}
                {{--<th>@sortablelink('confirmed', __('views.admin.users.index.table_header_4'),['page' => $users->currentPage()])</th>--}}
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->mobile_number }}</td>
                    <td>{{ $user->name }}</td>
                    <td>
                        <h4>
                            {{--{{ $user->roles->pluck('name')->implode(',') }}--}}
                            @if($user->hasRole('administrator'))
                                <i class="fa fa-lock" title="Administrator"></i>
                            @endif
                            @if($user->hasRole('owner'))
                                <i class="fa fa-cutlery" title="Store"></i>
                            @endif
                            @if($user->hasRole('delivery'))
                                <i class="fa fa-motorcycle" title="Delivery Executive"></i>
                            @endif
                            @if($user->hasRole('customer'))
                                <i class="fa fa-user-o" title="Customer"></i>
                            @endif
                        </h4>
                    </td>
                    <td>
                        @if($user->mobile_verified)
                            <span class="label label-primary"><i class="fa fa-check"></i></span>
                        @else
                            <span class="label label-danger"><i class="fa fa-times"></i></span>
                        @endif
                    </td>
                    <td>
                        @if($user->hasRole('owner') && $user->store)
                            <a href="{{ route('admin.orders', ["store" => $user->store->id]) }}">Orders</a> |
                            <a href="{{ route('admin.earnings', ["user_id" => $user->id]) }}">Earnings</a> |
                            <a href="{{ route('admin.bankdetails', ["user" => $user->id]) }}">Bank Details</a>
                            <br/>
                            <a href="{{ route('admin.stores', ["store" => $user->store->id]) }}">Store</a> |
                            <a href="{{ route('admin.menuitems', ["store" => $user->store->id]) }}">Menu Items</a> |
                            <a href="{{ route('admin.ratings', ["store" => $user->store->id]) }}">Ratings</a>
                        @endif
                            @if($user->hasRole('delivery') && $user->deliveryProfile)
                                <a href="{{ route('admin.orders', ["delivery_profile_id" => $user->deliveryProfile->id]) }}">Orders</a> |
                                <a href="{{ route('admin.delivery_profiles', ["delivery_profile_id" => $user->deliveryProfile->id]) }}">Delivery Profile</a> |
                                <a href="{{ route('admin.earnings', ["user_id" => $user->id]) }}">Earnings</a> |
                            @endif
                        @if($user->hasRole('customer'))
                            <a href="{{ route('admin.orders', ["user" => $user->id]) }}">Orders</a>
                        @endif
                    </td>
                    {{--<td>--}}
                    {{--@if($user->confirmed)--}}
                    {{--<span class="label label-success">{{ __('views.admin.users.index.confirmed') }}</span>--}}
                    {{--@else--}}
                    {{--<span class="label label-warning">{{ __('views.admin.users.index.not_confirmed') }}</span>--}}
                    {{--@endif</td>--}}
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.users.show', [$user->id]) }}"
                           data-toggle="tooltip" data-placement="top"
                           data-title="{{ __('views.admin.users.index.show') }}">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-xs btn-info" href="{{ route('admin.users.edit', [$user->id]) }}"
                           data-toggle="tooltip" data-placement="top"
                           data-title="{{ __('views.admin.users.index.edit') }}">
                            <i class="fa fa-pencil"></i>
                        </a>
                        @if(!$user->hasRole('administrator'))
                        <a class="btn btn-xs btn-danger user_destroy delete" href="{{ route('admin.users.destroy', [$user->id]) }}"
                           data-toggle="tooltip" data-placement="top" data-title="{{ __('views.admin.users.index.delete') }}">
                        <i class="fa fa-trash"></i>
                        </a>
                        @endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            {{ $users->links() }}
        </div>
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('admin.layouts.admin')

@section('title', __('views.admin.users.show.title', ['name' => $user->name]))

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>
            <tr>
                <th>{{ __('views.admin.users.show.table_header_1') }}</th>
                <td>{{ $user->name }}</td>
            </tr>
            <tr>
                <th>{{ __('views.admin.users.show.table_header_2') }}</th>
                <td>
                    <a href="mailto:{{ $user->email }}">
                        {{ $user->email }}
                    </a>
                </td>
            </tr>
            <tr>
                <th>Mobile</th>
                <td>{{ $user->mobile_number }}</td>
            </tr>
            <tr>
                <th>Mobile Verified</th>
                <td>
                    @if($user->mobile_verified)
                        <span class="label label-primary"><i class="fa fa-check"></i></span>
                    @else
                        <span class="label label-danger"><i class="fa fa-times"></i></span>
                    @endif
                </td>
            </tr>
            <tr>
                <th>{{ __('views.admin.users.show.table_header_3') }}</th>
                <td>
                    {{ $user->roles->pluck('name')->implode(',') }}
                </td>
            </tr>
            {{--<tr>--}}
                {{--<th>{{ __('views.admin.users.show.table_header_4') }}</th>--}}
                {{--<td>--}}
                    {{--@if($user->active)--}}
                        {{--<span class="label label-primary">{{ __('views.admin.users.show.active') }}</span>--}}
                    {{--@else--}}
                        {{--<span class="label label-danger">{{ __('views.admin.users.show.inactive') }}</span>--}}
                    {{--@endif--}}
                {{--</td>--}}
            {{--</tr>--}}

            {{--<tr>--}}
                {{--<th>{{ __('views.admin.users.show.table_header_5') }}</th>--}}
                {{--<td>--}}
                    {{--@if($user->confirmed)--}}
                        {{--<span class="label label-success">{{ __('views.admin.users.show.confirmed') }}</span>--}}
                    {{--@else--}}
                        {{--<span class="label label-warning">{{ __('views.admin.users.show.not_confirmed') }}</span>--}}
                    {{--@endif</td>--}}
                {{--</td>--}}
            {{--</tr>--}}

            <tr>
                <th>{{ __('views.admin.users.show.table_header_6') }}</th>
                <td>{{ $user->created_at }} ({{ $user->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>{{ __('views.admin.users.show.table_header_7') }}</th>
                <td>{{ $user->updated_at }} ({{ $user->updated_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>Links</th>
                <td>
                    @if($user->hasRole('owner'))
                        <a href="{{ route('admin.orders', ["store" => $user->store->id]) }}">Orders</a> |
                        <a href="{{ route('admin.earnings', ["user_id" => $user->id]) }}">Earnings</a> |
                        <a href="{{ route('admin.bankdetails', ["user" => $user->id]) }}">Bank Details</a>
                        <br/>
                        <a href="{{ route('admin.stores', ["store" => $user->store->id]) }}">Store</a> |
                        <a href="{{ route('admin.menuitems', ["store" => $user->store->id]) }}">Menu Items</a> |
                        <a href="{{ route('admin.ratings', ["store" => $user->store->id]) }}">Ratings</a>
                    @endif
                    @if($user->hasRole('delivery'))
                        <a href="{{ route('admin.orders', ["delivery_profile_id" => $user->deliveryProfile->id]) }}">Orders</a> |
                        <a href="{{ route('admin.delivery_profiles', ["delivery_profile_id" => $user->deliveryProfile->id]) }}">Delivery Profile</a> |
                        <a href="{{ route('admin.earnings', ["user_id" => $user->id]) }}">Earnings</a> |
                    @endif
                    @if($user->hasRole('customer'))
                        <a href="{{ route('admin.orders', ["user" => $user->id]) }}">Orders</a>
                    @endif
                </td>
            </tr>
            <tr>
                <td><a class="btn btn-primary" href="{{ URL::previous() }}"> Back</a></td>
            </tr>
            </tbody>
        </table>
    </div>
@endsection