routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Auth routes
 */
Route::group(['namespace' => 'Auth'], function () {

    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    // Registration Routes...
    if (config('auth.users.registration')) {
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
    }

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset');

    // Confirmation Routes...
    if (config('auth.users.confirm_email')) {
        Route::get('confirm/{user_by_code}', 'ConfirmController@confirm')->name('confirm');
        Route::get('confirm/resend/{user_by_email}', 'ConfirmController@sendEmail')->name('confirm.send');
    }

    // Social Authentication Routes...
    Route::get('social/redirect/{provider}', 'SocialLoginController@redirect')->name('social.redirect');
    Route::get('social/login/{provider}', 'SocialLoginController@login')->name('social.login');
});

/**
 * Backend routes
 */
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    // Dashboard
    Route::get('/', 'DashboardController@index')->name('dashboard');

    Route::group(['middleware' => 'admin'], function () {
        //Users
        Route::get('users', 'UserController@index')->name('users');
        Route::get('users/create', 'UserController@create')->name('users.create');
        Route::post('users', 'UserController@store')->name('users.store');
        Route::get('users/{user}', 'UserController@show')->name('users.show');
        Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
        Route::put('users/{user}', 'UserController@update')->name('users.update');
        Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');

        Route::get('permissions', 'PermissionController@index')->name('permissions');
        Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');

        Route::get('dashboard/log-chart', 'DashboardController@getLogChartData')->name('dashboard.log.chart');
        Route::get('dashboard/registration-chart', 'DashboardController@getRegistrationChartData')->name('dashboard.registration.chart');

        Route::get('deliveryProfiles', 'DeliveryProfileController@index')->name('delivery_profiles');
        Route::get('deliveryProfiles/{deliveryProfile}', 'DeliveryProfileController@show')->name('delivery_profiles.show');
        Route::get('deliveryProfiles/{deliveryProfile}/edit', 'DeliveryProfileController@edit')->name('delivery_profiles.edit');
        Route::put('deliveryProfiles/{deliveryProfile}', 'DeliveryProfileController@update')->name('delivery_profiles.update');

        Route::get('supports', 'SupportController@index')->name('supports');
        Route::get('supports/{support}', 'SupportController@show')->name('supports.show');

        Route::get('categories', 'CategoryController@index')->name('categories');
        Route::get('categories/create', 'CategoryController@create')->name('categories.create');
        Route::post('categories', 'CategoryController@store')->name('categories.store');
        Route::get('categories/{category}/edit', 'CategoryController@edit')->name('categories.edit');
        Route::put('categories/{category}', 'CategoryController@update')->name('categories.update');

        Route::get('coupons', 'CouponController@index')->name('coupons');
        Route::get('coupons/create', 'CouponController@create')->name('coupons.create');
        Route::post('coupons', 'CouponController@store')->name('coupons.store');
        Route::get('coupons/{coupon}/edit', 'CouponController@edit')->name('coupons.edit');
        Route::put('coupons/{coupon}', 'CouponController@update')->name('coupons.update');
        Route::delete('coupons/{coupon}', 'CouponController@destroy')->name('coupons.destroy');

        Route::get('menuitems', 'MenuItemController@index')->name('menuitems');
        Route::get('menuitems/create', 'MenuItemController@create')->name('menuitems.create');
        Route::post('menuitems', 'MenuItemController@store')->name('menuitems.store');
        Route::get('menuitems/{menuitem}', 'MenuItemController@show')->name('menuitems.show');
        Route::get('menuitems/{menuitem}/edit', 'MenuItemController@edit')->name('menuitems.edit');
        Route::put('menuitems/{menuitem}', 'MenuItemController@update')->name('menuitems.update');
        Route::put('menuitems/{menuitem}/quick-approve', 'MenuItemController@quickApprove')->name('menuitems.quickApprove');

        #Route::get('settings', 'SettingController@index')->name('settings');
        Route::get('settings/{setting}/edit', 'SettingController@edit')->name('settings.edit');
        Route::get('settings', 'SettingController@settings')->name('settings');
        Route::put('settings/update-env', 'SettingController@updateEnv')->name('settings.updateEnv');
        Route::put('settings/update-setting', 'SettingController@updateSetting')->name('settings.updateSetting');

        Route::post('json/notifications/read', 'Json\NotificationController@readNotifications')->name('json.notifications.read');
        Route::post('json/notifications/delete', 'Json\NotificationController@deleteNotifications')->name('json.notifications.delete');
        Route::post('json/dashboard/orders-chart-data', 'Json\DashboardController@ordersChartData')->name('json.dashboard.ordersChartData');
        Route::post('json/dashboard/users-chart-data', 'Json\DashboardController@usersChartData')->name('json.dashboard.usersChartData');
        Route::put('json/orders/{order}', 'Json\OrderController@update')->name('json.orders.update');
    });

    Route::group(['middleware' => 'store'], function () {
        Route::get('stores', 'StoreController@index')->name('stores');
        Route::get('stores/{store}', 'StoreController@show')->name('stores.show');
        Route::get('stores/{store}/edit', 'StoreController@edit')->name('stores.edit');
        Route::put('stores/{store}', 'StoreController@update')->name('stores.update');

        Route::get('menuitems', 'MenuItemController@index')->name('menuitems');
        Route::get('menuitems/{menuitem}', 'MenuItemController@show')->name('menuitems.show');
        Route::get('menuitems/{menuitem}/edit', 'MenuItemController@edit')->name('menuitems.edit');
        Route::put('menuitems/{menuitem}', 'MenuItemController@update')->name('menuitems.update');

        Route::get('ratings', 'RatingController@index')->name('ratings');
        Route::get('ratings/{id}', 'RatingController@destroy')->name('ratings.destroy');

        Route::get('orders', 'OrderController@index')->name('orders');
        Route::get('orders/{order}', 'OrderController@show')->name('orders.show');
        Route::get('orders/{order}/edit', 'OrderController@edit')->name('orders.edit');
        Route::put('orders/{order}', 'OrderController@update')->name('orders.update');

        Route::get('earnings', 'EarningController@index')->name('earnings');
        Route::get('earnings/{earning}', 'EarningController@show')->name('earnings.show');

        Route::get('ratings', 'RatingController@index')->name('ratings');
        Route::get('ratings/{id}', 'RatingController@destroy')->name('ratings.destroy');

        Route::get('bankdetails', 'BankDetailController@index')->name('bankdetails');
        Route::get('bankdetails/{bankdetail}', 'BankDetailController@show')->name('bankdetails.show');
        Route::get('bankdetails/{bankdetail}/edit', 'BankDetailController@edit')->name('bankdetails.edit');
        Route::put('bankdetails/{bankdetail}', 'BankDetailController@update')->name('bankdetails.update');
    });
});


Route::get('/', 'HomeController@index');

app/Http/Controllers/Admin/Json/OrderController.php
<?php

namespace App\Http\Controllers\Admin\Json;

use App\Events\Auth\Registered;
use App\Events\Ordered;
use App\Http\Requests\Admin\UserRequest;
use App\Http\Requests\ApiOrderUpdateRequest;
use App\Models\Auth\Role\Role;
use App\Models\Auth\User\User;
use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\UnauthorizedException;
use Validator;

class OrderController extends Controller
{
    /**
     * Update order status
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(ApiOrderUpdateRequest $request, Order $order)
    {
        if($request->status == 'dispatched' && !$order->delivery_profile_id) {
            // if store is trying to update the status of order to `dispatched`, first check if delivery person is assigned
            // to the order, if yes, simply update the order status, if no, try to allot delivery person to the order
            // if success, return 422 status code implying we have allotted the delivery person but order is not yet dispatched,
            // if we don't find any delivery person yet return status code 404
            if($order->allotDeliveryPerson($order)) {
                return response()->json($order->refresh(), 422);
            };
            return response()->json($order, 404);
        }
        $order->fill($request->all());
        $order->save();

        event(new Ordered($order, true));

        return response()->json($order);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\OrderUpdateRequest;
use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $orders = Order::whereRaw('1=1');

        $currentStore = admin_get_store();
        if($currentStore) {
            $orders = $orders->where('store_id', $currentStore->id);
        }

        if ($request->user) {
            $orders = $orders->where('user_id', $request->user);
        }

        if ($request->store) {
            $orders = $orders->where('store_id', $request->store);
        }

        if ($request->delivery_profile_id) {
            $orders = $orders->where('delivery_profile_id', $request->delivery_profile_id);
        }

        if ($request->status) {
            $orders = $orders->where('status', $request->status);
        }

        if ($request->delivery_status) {
            $orders = $orders->where('delivery_status', $request->delivery_status);
        }

        if ($request->payment_status) {
            $orders = $orders->where('payment_status', $request->payment_status);
        }

        if ($request->input('from')) {
            $orders = $orders->where('created_at', '>=', $request->input('from'));
        }

        if ($request->input('to')) {
            $orders = $orders->where('created_at', '<=', $request->input('to'));
        }

        // keyword search
        if ($request->search) {
            $orders = $orders->where(function ($query) use ($request) {
                $query->whereHas('user', function ($subquery) use ($request) {
                    $subquery->where('name', 'like', '%' . $request->search . '%')
                        ->orWhere('email', 'like', '%' . $request->search . '%')
                        ->orWhere('mobile_number', 'like', '%' . $request->search . '%');
                })
                    ->orWhereHas('store', function ($subquery) use ($request) {
                        $subquery->where('name', 'like', '%' . $request->search . '%')
                            ->orWhere('tagline', 'like', '%' . $request->search . '%')
                            ->orWhere('address', 'like', '%' . $request->search . '%')
                            ->orWhere('area', 'like', '%' . $request->search . '%')
                            ->orWhere('details', 'like', '%' . $request->search . '%');
                    })
                    ->orWhereHas('address', function ($subquery) use ($request) {
                        $subquery->where('address', 'like', '%' . $request->search . '%');
                    })
                    ->orWhere('total', $request->search);
            });
        }

        return view('admin.orders.index', ['orders' => $orders->orderBy('created_at', 'desc')->paginate()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Ordered a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param Order $order
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Order $order)
    {
        admin_authorize_store($order->store_id);

        return view('admin.orders.show', ['order' => $order]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Order $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('admin.orders.edit', ['order' => $order]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param OrderUpdateRequest $request
     * @param Order $order
     * @return mixed
     */
    public function update(OrderUpdateRequest $request, Order $order)
    {
        $order->fill($request->all());
        $order->save();

        return redirect()->intended(route('admin.orders'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Api/Delivery/OrderController.php
<?php

namespace App\Http\Controllers\Api\Delivery;

use App\Events\Ordered;
use App\Http\Controllers\Controller;
use App\Http\Requests\ApiOrderUpdateRequest;
use App\Http\Requests\Customer\ApiOrderCreateRequest;
use App\Models\DeliveryProfile;
use App\Models\Earning;
use App\Models\Order;
use App\Models\Setting;
use App\Models\Store;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    /**
     * Get orders by store_id
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function showAvailableOrder(Request $request)
    {
        $order = Order::where('delivery_profile_id', Auth::user()->deliveryProfile->id)
            ->whereIn('delivery_status', ['pending', 'allotted', 'started'])
            ->first();
        if($order) {
            return response()->json($order);
        }
        return response()->json(['message' => 'No Ordered assigned'], 404);
    }

    public function updateDeliveryStatus(Order $order, Request $request) {
        if(!in_array($request->delivery_status, ['pending', 'allotted', 'started', 'cancelled', 'complete'])) {
            return response()->json(['error' => 'Invalid delivery status'], 400);
        }
        $order->delivery_status = $request->delivery_status;

        $order->save();

        event(new Ordered($order));

        return response()->json($order);
    }
}

resources/views/admin/orders/index.blade.php
    @extends('admin.layouts.admin')

@section('title', "Orders")

@section('content')
    <div class="col-md-12 col-sm-12 col-xs-12">

        {{ Form::open(['url'=>url()->full(),'method' => 'get','class'=>'form-horizontal form-label-left']) }}
        <input type="hidden" name="status" value="{{request()->input('status')}}">
        <input type="hidden" name="delivery_status" value="{{request()->input('delivery_status')}}">
        <input type="hidden" name="payment_status" value="{{request()->input('payment_status')}}">

        <div class="">
            <strong>Order Status: </strong>
            <a class="btn btn-primary" href="{{ app('request')->fullUrlWithQuery(['status' => 'new'])  }}">New</a>
            <a class="btn btn-warning" href="{{ app('request')->fullUrlWithQuery(['status' => 'pending'])  }}">Pending</a>
            <a class="btn btn-danger" href="{{ app('request')->fullUrlWithQuery(['status' => 'cancelled'])  }}">Cancelled</a>
            <a class="btn btn-success" href="{{ app('request')->fullUrlWithQuery(['status' => 'accepted'])  }}">Accepted</a>
            <a class="btn btn-danger" href="{{ app('request')->fullUrlWithQuery(['status' => 'rejected'])  }}">Rejected</a>
            <a class="btn btn-info" href="{{ app('request')->fullUrlWithQuery(['status' => 'preparing'])  }}">Preparing</a>
            <a class="btn btn-info" href="{{ app('request')->fullUrlWithQuery(['status' => 'dispatched'])  }}">Dispatched</a>
            <a class="btn btn-info" href="{{ app('request')->fullUrlWithQuery(['status' => 'intransit'])  }}">Intransit</a>
            <a class="btn btn-success" href="{{ app('request')->fullUrlWithQuery(['status' => 'complete'])  }}">Complete</a>
            <a title="Clear" class="btn btn-default" href="{{ url_without_query_param('status')  }}"><i class="fa fa-remove"></i></a>
        </div>
        <div class="">
            <strong>Delivery Status: </strong> &nbsp;
            <a class="btn btn-warning" href="{{ app('request')->fullUrlWithQuery(['delivery_status' => 'pending'])  }}">Pending</a>
            <a class="btn btn-success" href="{{ app('request')->fullUrlWithQuery(['delivery_status' => 'allotted'])  }}">Allotted</a>
            <a class="btn btn-info" href="{{ app('request')->fullUrlWithQuery(['delivery_status' => 'started'])  }}">Started</a>
            <a class="btn btn-danger" href="{{ app('request')->fullUrlWithQuery(['delivery_status' => 'cancelled'])  }}">Cancelled</a>
            <a class="btn btn-success" href="{{ app('request')->fullUrlWithQuery(['delivery_status' => 'complete'])  }}">Complete</a>
            <a title="Clear" class="btn btn-default" href="{{ url_without_query_param('delivery_status')  }}"><i class="fa fa-remove"></i></a>
        </div>
        <div class="">
            <strong>Payment Status: </strong>
            <a class="btn btn-warning" href="{{ app('request')->fullUrlWithQuery(['payment_status' => 'paid'])  }}">Paid</a>
            <a class="btn btn-success" href="{{ app('request')->fullUrlWithQuery(['payment_status' => 'unpaid'])  }}">Unpaid</a>
            <a title="Clear" class="btn btn-default" href="{{ url_without_query_param('payment_status')  }}"><i class="fa fa-remove"></i></a>
        </div>

        <div class="form-group" style="margin: 30px 0 30px 0;">
            <label class="control-label col-sm-2 col-xs-12">
                Order Create Date:
            </label>
            <div class="col-sm-3 col-xs-12">
                <input id="from" type="date" class="form-control col-md-7 col-xs-12" placeholder="Date From"
                       name="from" value="{{ app('request')->input('from')  }}">
            </div>
            <div class="col-sm-3 col-xs-12">
                <input id="to" type="date" class="form-control col-md-7 col-xs-12" placeholder="Date To"
                       name="to" value="{{ app('request')->input('to')  }}">
            </div>
            <div class="col-sm-4 col-xs-12">
                <button type="submit" class="btn btn-success"><i class="fa fa-search"></i> Filter</button>
                <a title="Clear" class="btn btn-default" href="{{ url_without_query_param(['from', 'to'])  }}"><i class="fa fa-remove"></i></a>
            </div>
        </div>


        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="form-group">
                <label class="control-label col-sm-3 col-xs-12" for="search">
                    Search
                </label>
                <div class="col-sm-4 col-xs-12">
                    <input id="search" type="text" class="form-control col-md-7 col-xs-12"
                           placeholder="Search user, store, address, total"
                           name="search" required value="{{ app('request')->input('search')  }}">
                </div>
                <div class="col-sm-5 col-xs-12">
                    <button type="submit" class="btn btn-success"><i class="fa fa-search"></i> Filter</button>
                    <a title="Clear" class="btn btn-default" href="{{ url_without_query_param('search')  }}"><i
                                class="fa fa-remove"></i></a>
                </div>
            </div>
            <div class="form-group">

            </div>
        </div>

        {{ Form::close() }}
    </div>


    <div class="row">
        <table class="table table-striped table-bordered dt-responsive nowrap jambo_table" cellspacing="0"
               width="100%">
            <thead>
            <tr>
                <th>User ID</th>
                <th>Store ID</th>
                <th>Total</th>
                <th>Status</th>
                <th>Delivery Status</th>
                <th>Payment Status</th>
                <th>Delivery At</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
                <tr>
                    <td><a href="{{ route('admin.users.show', [$order->user_id]) }}">{{ $order->user->name }}</a></td>
                    <td><a href="{{ route('admin.stores.show', [$order->store_id]) }}">{{ $order->store->name }}</a></td>
                    <td>{{ $order->total }}</td>
                    <td>{{ $order->status }}</td>
                    <td>{{ $order->delivery_status }}</td>
                    <td>{{ $order->payment_status }}</td>
                    <td>
                        <a href="https://www.google.com/maps/search/?api=1&query={{ $order->address->latitude . "," . $order->address->longitude }}" target="_blank">
                            {{ $order->address->address }}
                        </a>
                    </td>
                    <td>{{ $order->created_at->toDayDateTimeString() }}</td>
                    <td>{{ $order->updated_at->toDayDateTimeString() }}</td>
                    <td>
                        <a class="btn btn-xs btn-primary" href="{{ route('admin.orders.show', [$order->id]) }}" data-toggle="tooltip" data-placement="top">
                            <i class="fa fa-eye"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="pull-right">
            {{ $orders->links() }}
        </div>
    </div>
@endsection

resources/views/admin/orders/show.blade.php
@extends('admin.layouts.admin')

@section('title', 'View'))

@section('content')
    <div class="row">
        <table class="table table-striped table-hover">
            <tbody>

            <tr>
                <th>User</th>
                <td><a target="_blank"
                       href="{{ route('admin.users.show', [$order->owner_id]) }}">{{ $order->user->name  }}</a></td>
            </tr>

            <tr>
                <th>Store</th>
                <td><a target="_blank"
                       href="{{ route('admin.stores.show', [$order->owner_id]) }}">{{ $order->store->name  }}</a></td>
            </tr>

            <tr>
                <th>Delivery Person</th>
                <td>
                    @if($order->delivery_profile_id)
                        <a target="_blank"
                           href="{{ route('admin.delivery_profiles.show', [$order->delivery_profile_id]) }}">{{ $order->deliveryProfile->user->name  }}</a>
                    @else
                        Not Assigned
                    @endif

                </td>
            </tr>

            <tr>
                <th>Subtotal</th>
                <td>{{ $order->subtotal }}</td>
            </tr>

            <tr>
                <th>Taxes</th>
                <td>{{ $order->taxes }}</td>
            </tr>

            <tr>
                <th>Delivery Fee</th>
                <td>{{ $order->delivery_fee }}</td>
            </tr>

            <tr>
                <th>Total</th>
                <td>{{ $order->total }}</td>
            </tr>

            <tr>
                <th>Discount</th>
                <td>{{ $order->discount }}</td>
            </tr>

            <tr>
                <th>Status</th>
                <td>{{ $order->status }}</td>
            </tr>

            <tr>
                <th>Delivery Status</th>
                <td>{{ $order->delivery_status }}</td>
            </tr>

            <tr>
                <th>Payment Status</th>
                <td>{{ $order->payment_status }}</td>
            </tr>

            <tr>
                <th>Payment Method</th>
                <td>{{ $order->paymentMethod->title }}</td>
            </tr>

            <tr>
                <th>Special Instructions</th>
                <td>{{ $order->special_instructions }}</td>
            </tr>

            <tr>
                <th>Address</th>
                <td>
                    <a href="https://www.google.com/maps/search/?api=1&query={{ $order->address->latitude . "," . $order->address->longitude }}"
                       target="_blank">
                        {{ $order->address->address }}
                    </a>
                </td>
            </tr>

            <tr>
                <th>Created At</th>
                <td>{{ $order->created_at->toDayDateTimeString() }} ({{ $order->created_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>Updated At</th>
                <td>{{ $order->updated_at->toDayDateTimeString() }} ({{ $order->updated_at->diffForHumans() }})</td>
            </tr>

            <tr>
                <th>Updated Status</th>
                <td>
                    @if(in_array($order->status, ['new', 'pending']))
                        <button id="update-status" class="btn btn-success" data-status="accepted">Accept Order</button>
                    @endif
                    @if($order->status == 'accepted')
                        <button id="update-status" class="btn btn-success" data-status="dispatched">Dispatch Order</button>
                    @endif
                </td>
            </tr>

            <tr>
                <th class="col-xs-2">Location on map</th>
                <td>
                    <div id="map" style="height: 600px;"></div>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
@endsection

@section('scripts')
    @parent

    <script>
        // map
        var map;
        var marker;
        var storeMarker;
        var deiveryMarker;
        var deliveryAssigned = @if($order->delivery_profile_id) true; @else false; @endif
        var deliveryLat = @if($order->delivery_profile_id) {{$order->deliveryProfile->latitude}}; @else null; @endif
        var deliveryLng = @if($order->delivery_profile_id) {{$order->deliveryProfile->longitude}}; @else null; @endif

        function initMap() {
            var myLatLng = {
                lat: parseFloat('{{ $order->address->latitude }}'),
                lng: parseFloat('{{ $order->address->longitude }}')
            };

            var storeLatLng = {
                lat: parseFloat('{{ $order->store->latitude }}'),
                lng: parseFloat('{{ $order->store->longitude }}')
            };

            var deliveryLatLng = deliveryAssigned ? {
                lat: parseFloat(deliveryLat),
                lng: parseFloat(deliveryLng)
            } : null;

            map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: myLatLng
            });

            marker = new google.maps.Marker({
                map: map,
                position: myLatLng
            });

            marker = new google.maps.Marker({
                map: map,
                position: storeLatLng,
                icon: 'http://localhost/chefqu/public/assets/store.png'
            });

            if(deliveryLatLng != null) {
                deiveryMarker = new google.maps.Marker({
                    map: map,
                    position: deliveryLatLng,
                    icon: 'http://localhost/chefqu/public/assets/bike.png'
                });
            }
        }
    </script>

    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBQgDBgxgMLaf2Xp173VIhuKVzAw_vPCyY&callback=initMap"
            type="text/javascript"></script>

    <script type="text/javascript">
        $("#update-status").on('click', (function (event) {
            var elem = this;
            $.ajax({
                type: 'PUT',
                url: "{{ route('admin.json.orders.update', ['order' => $order->id]) }}",
                data: {status: $(elem).attr("data-status")},
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                dataType: 'json'
            }).done(function (data) {
                alert('Order status updated successfully!');
                window.location.reload();
            }).fail(function(err) {
                if(err.status == 404) {
                    alert('Delivery person not assigned. Unable to dispatch order.');
                }
                if(err.status == 422) {
                    alert('Just assigned delivery person. Please wait till he reaches your store to dispatch order.');
                    window.location.reload();
                }
            });
        }));
    </script>
@endsection